name: Link Checker

on:
  schedule:
    - cron: '0 2 * * *' # daily at 2 AM UTC
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: >
            --verbose
            --retry-wait-time 10
            --max-retries 3
            --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
            README.md
